from mpi4py import MPI
import numpy as np
import time

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

def calculate_fitness(route, distance_matrix):
    """
    Calculates the total distance traveled by the car.

    Parameters:
        - route (list): Order of nodes visited in the route.
        - distance_matrix (numpy.ndarray): Matrix of distances between nodes.

    Returns:
        - float: Negative total distance traveled (negative because we minimize distance).
        - Returns a scaled penalty if the route is infeasible.
    """
    total_distance = 0

    for i in range(len(route) - 1):
        node1, node2 = route[i], route[i + 1]
        distance = distance_matrix[node1][node2]

        if distance == 100000:  # Penalty for infeasible routes
            total_distance += np.median(distance_matrix[distance_matrix < 100000]) * 2  
        else:
            total_distance += distance

    return -total_distance  # Negative for minimization


def select_in_tournament(population, scores, number_tournaments=12, tournament_size=8):
    """
    Tournament selection for genetic algorithm.

    Parameters:
        - population (list): Current population of routes.
        - scores (np.array): Fitness scores of each route.
        - number_tournaments (int): Number of tournaments to run.
        - tournament_size (int): Number of individuals per tournament.

    Returns:
        - list: Selected individuals for crossover.
    """
    selected = []

    for _ in range(number_tournaments):
        idx = np.random.choice(len(population), tournament_size, replace=False)
        best_idx = idx[np.argmax(scores[idx])]
        selected.append(population[best_idx])

    return selected


def order_crossover(parent1, parent2):
    """
    Order crossover (OX) for permutations.

    Parameters:
        - parent1 (list): The first parent route.
        - parent2 (list): The second parent route.

    Returns:
        - list: The offspring route generated by the crossover.
    """
    size = len(parent1)
    start, end = sorted(np.random.choice(range(size), 2, replace=False))
    offspring = [None] * size
    offspring[start:end + 1] = parent1[start:end + 1]
    fill_values = [x for x in parent2 if x not in offspring[start:end + 1]]
    idx = 0
    for i in range(size):
        if offspring[i] is None:
            offspring[i] = fill_values[idx]
            idx += 1
    return offspring


def mutate(route, mutation_rate=1.5):
    """
    Mutation operator: swap two nodes in the route.

    Parameters:
        - route (list): The route to mutate.
        - mutation_rate (float): The chance to mutate an individual.

    Returns:
        - list: The mutated route.
    """
    if np.random.rand() < mutation_rate:
        i, j = np.random.choice(len(route), 2, replace=False)
        route[i], route[j] = route[j], route[i]
    return route


def generate_unique_population(population_size, num_nodes):
    """
    Generate a unique population of individuals for a genetic algorithm.

    Each individual in the population represents a route in a graph, where the first node is fixed (0) and the 
    remaining nodes are a permutation of the other nodes in the graph. This function ensures that all individuals
    in the population are unique.

    Parameters:
        - population_size (int): The desired size of the population.
        - num_nodes (int): The number of nodes in the graph, including the starting node.

    Returns:
        - list of lists: A list of unique individuals, where each individual is represented as a list of node indices.
    """
    population = set()
    while len(population) < population_size:
        individual = [0] + list(np.random.permutation(np.arange(1, num_nodes)))
        population.add(tuple(individual))
    return [list(ind) for ind in population]


def run_genetic_algorithm(population, distance_matrix, num_generations, stagnation_limit):
    """
    Runs the genetic algorithm in parallel and measures execution time.

    Parameters:
    - population: The initial population
    - distance_matrix: Distance matrix for calculating fitness
    - num_generations: Number of generations
    - stagnation_limit: Stagnation limit before regenerating population

    Returns:
    - Best solution and execution time
    """
    start_time = time.time()  # Start Timer

    best_fitness = float("inf")
    stagnation_counter = 0

    for generation in range(num_generations):
        fitness_values = np.array([calculate_fitness(route, distance_matrix) for route in population])

        # Parallel processing: Scatter and Gather
        local_population_size = len(population) // size
        local_population = comm.scatter(population[:local_population_size * size], root=0)
        local_fitness = np.array([calculate_fitness(route, distance_matrix) for route in local_population])
        gathered_fitness = comm.gather(local_fitness, root=0)

        if rank == 0:
            fitness_values = np.concatenate(gathered_fitness)

        current_best_fitness = np.min(fitness_values)
        if current_best_fitness < best_fitness:
            best_fitness = current_best_fitness
            stagnation_counter = 0
        else:
            stagnation_counter += 1

        if stagnation_counter >= stagnation_limit:
            print(f"Regenerating population at generation {generation} due to stagnation")
            best_individual = population[np.argmin(fitness_values)]
            population = generate_unique_population(len(population) - 1, len(distance_matrix))
            population.append(best_individual)
            stagnation_counter = 0
            continue

        selected = select_in_tournament(population, fitness_values)
        offspring = [mutate(order_crossover(selected[i], selected[i + 1]), 0.1) for i in range(0, len(selected), 2)]
        population = offspring

        print(f"Generation {generation}: Best fitness = {current_best_fitness}")

    end_time = time.time()  # End Timer
    execution_time = end_time - start_time

    print(f"Execution Time: {execution_time:.2f} seconds")
    return best_fitness, execution_time
